version: 2

updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: monthly
      day: monday
    ignore:
      - dependency-name: "@types/vscode"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"